import type { TaskSpec } from "../../types.js";
import {
  TEAM3_MAIL_TASKS,
  mailExtract2faCodeTask,
  mailExtractCancellationFeeTask,
  mailExtractDeadlineTask,
  mailExtractDraftRecipientTask,
  mailExtractExceptionNameTask,
  mailExtractFlightPnrTask,
  mailExtractHrPhoneTask,
  mailExtractInvoiceTask,
  mailExtractMeetingTimeTask,
  mailExtractMessyReceiptTask,
  mailExtractPromoCodeTask,
  mailExtractRebookedFlightTask,
  mailExtractResetLinkTask,
  mailExtractSpamSenderTask,
  mailExtractSshIpTask,
  mailExtractTrackingTask,
  mailExtractTrashLinkTask,
  mailExtractUnsubscribeLinkTask,
  mailRecordSenderAddressTask
} from "./mail.js";
import {
  TEAM3_TERMINAL_TASKS,
  team3TerminalRecordWorkingDirectoryTask,
  terminalCatAndSaveConfigTask,
  terminalCatCertExpiryTask,
  terminalCatCsvEmailTask,
  terminalCatCsvSpecificValueTask,
  terminalCatEnvPasswordTask,
  terminalCatGitignoreTask,
  terminalCatHiddenCredentialsTask,
  terminalCatJsonNestedTask,
  terminalCatLogErrorCodeTask,
  terminalCatPackageJsonVersionTask,
  terminalCatProcessListTask,
  terminalCatPythonImportTask,
  terminalCatYamlConfigTask,
  terminalFindBackupFileTask,
  terminalFindShellScriptTask,
  terminalFindSpecificExtensionTask,
  terminalListDirTask,
  terminalListHiddenFilesTask,
  terminalListLogDirTask,
  terminalRecordDeepPwdTask
} from "./terminal.js";

export {
  mailExtractInvoiceTask,
  terminalListDirTask,
  team3TerminalRecordWorkingDirectoryTask,
  terminalCatAndSaveConfigTask,
  mailRecordSenderAddressTask,
  mailExtractResetLinkTask,
  mailExtractMeetingTimeTask,
  mailExtractTrackingTask,
  mailExtractSpamSenderTask,
  mailExtract2faCodeTask,
  terminalCatEnvPasswordTask,
  terminalCatLogErrorCodeTask,
  terminalListLogDirTask,
  terminalCatCsvEmailTask,
  terminalRecordDeepPwdTask,
  mailExtractTrashLinkTask,
  mailExtractMessyReceiptTask,
  mailExtractFlightPnrTask,
  mailExtractExceptionNameTask,
  mailExtractSshIpTask,
  terminalCatHiddenCredentialsTask,
  terminalListHiddenFilesTask,
  terminalCatJsonNestedTask,
  terminalCatPythonImportTask,
  terminalFindSpecificExtensionTask,
  mailExtractCancellationFeeTask,
  mailExtractHrPhoneTask,
  mailExtractDraftRecipientTask,
  mailExtractPromoCodeTask,
  mailExtractDeadlineTask,
  terminalCatCsvSpecificValueTask,
  terminalCatGitignoreTask,
  terminalFindBackupFileTask,
  terminalCatPackageJsonVersionTask,
  terminalFindShellScriptTask,
  terminalCatProcessListTask,
  mailExtractRebookedFlightTask,
  terminalCatYamlConfigTask,
  mailExtractUnsubscribeLinkTask,
  terminalCatCertExpiryTask,
  TEAM3_MAIL_TASKS,
  TEAM3_TERMINAL_TASKS
};

export const TEAM3_TASKS: TaskSpec[] = [...TEAM3_MAIL_TASKS, ...TEAM3_TERMINAL_TASKS];
